"""create_initial_tables

Revision ID: 47a1c91bfecc
Revises: 
Create Date: 2025-05-28 14:52:10.156858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a1c91bfecc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('funding_amount', sa.Float(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'DRAFT', 'ARCHIVED', name='grantstatus'), nullable=True),
    sa.Column('eligibility', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grants_category'), 'grants', ['category'], unique=False)
    op.create_index(op.f('ix_grants_deadline'), 'grants', ['deadline'], unique=False)
    op.create_index(op.f('ix_grants_status'), 'grants', ['status'], unique=False)
    op.create_index(op.f('ix_grants_title'), 'grants', ['title'], unique=False)
    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('grants_found', sa.Integer(), nullable=True),
    sa.Column('high_priority', sa.Integer(), nullable=True),
    sa.Column('search_filters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=True),
    sa.Column('minimum_score', sa.Float(), nullable=True),
    sa.Column('notify_categories', sa.JSON(), nullable=True),
    sa.Column('schedule_frequency', sa.Enum('DAILY', 'WEEKLY', 'TWICE_WEEKLY', 'MONTHLY', name='searchfrequency'), nullable=True),
    sa.Column('schedule_days', sa.JSON(), nullable=True),
    sa.Column('schedule_time', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grant_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('analysis_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_score'), 'analyses', ['score'], unique=False)
    op.create_table('saved_grants',
    sa.Column('user_settings_id', sa.Integer(), nullable=False),
    sa.Column('grant_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['grants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_settings_id'], ['user_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_settings_id', 'grant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_grants')
    op.drop_index(op.f('ix_analyses_score'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_table('user_settings')
    op.drop_table('search_runs')
    op.drop_index(op.f('ix_grants_title'), table_name='grants')
    op.drop_index(op.f('ix_grants_status'), table_name='grants')
    op.drop_index(op.f('ix_grants_deadline'), table_name='grants')
    op.drop_index(op.f('ix_grants_category'), table_name='grants')
    op.drop_table('grants')
    # ### end Alembic commands ###
