"""Add overall_composite_score to Grant model

Revision ID: d896bf2738fb
Revises: a6d046fdb2d0
Create Date: 2025-06-07 17:59:02.098914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd896bf2738fb'
down_revision: Union[str, None] = 'a6d046fdb2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_history_grant_id'), table_name='application_history')
    op.drop_index(op.f('ix_application_history_status'), table_name='application_history')
    op.add_column('grants', sa.Column('overall_composite_score', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_grants_status'), table_name='grants')
    op.create_index(op.f('ix_grants_overall_composite_score'), 'grants', ['overall_composite_score'], unique=False)
    op.drop_column('grants', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grants', sa.Column('status', postgresql.ENUM('ACTIVE', 'EXPIRED', 'DRAFT', 'ARCHIVED', name='grantstatus'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_grants_overall_composite_score'), table_name='grants')
    op.create_index(op.f('ix_grants_status'), 'grants', ['status'], unique=False)
    op.drop_column('grants', 'overall_composite_score')
    op.create_index(op.f('ix_application_history_status'), 'application_history', ['status'], unique=False)
    op.create_index(op.f('ix_application_history_grant_id'), 'application_history', ['grant_id'], unique=False)
    # ### end Alembic commands ###
